# Generated by Django 6.1.1 on 2026-09-04 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('total_payments', models.PositiveIntegerField(default=0)),
                ('matched_pairs', models.PositiveIntegerField(default=0)),
                ('value_reconciled', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('value_in_dispute', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('money_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('breakdown', models.JSONField(default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='ingestion.importbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('missing_payment', 'Missing Payment'), ('orphan_charge', 'Orphan Charge'), ('duplicate_charge', 'Duplicate Charge'), ('amount_mismatch', 'Amount Mismatch'), ('charged_after_cancellation', 'Charged After Cancellation'), ('failed_payment', 'Failed Payment'), ('pending_payment', 'Pending Payment'), ('partial_refund', 'Partial Refund'), ('refund_of_completed_order', 'Refund Of Completed Order'), ('currency_mismatch', 'Currency Mismatch'), ('late_settlement', 'Late Settlement'), ('rounding_variance', 'Rounding Variance'), ('data_quality', 'Data Quality')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], max_length=8)),
                ('risk_bucket', models.CharField(blank=True, default='', max_length=32)),
                ('order_ref', models.CharField(db_index=True, max_length=64)),
                ('transaction_refs', models.JSONField(default=list)),
                ('amount_at_risk', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('detail', models.JSONField(default=dict)),
                ('explanation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['type', 'order_ref'],
                'indexes': [models.Index(fields=['run', 'type'], name='reconciliat_run_id_6f3fa9_idx'), models.Index(fields=['run', 'severity'], name='reconciliat_run_id_0c9804_idx')],
            },
        ),
    ]
