# Generated by Django 6.1.1 on 2026-09-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationrun',
            name='needs_investigation',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='refund_obligations',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='uncollected_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
