# Generated by Django 6.1.1 on 2026-09-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_reconciliationrun_needs_investigation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discrepancy',
            name='type',
            field=models.CharField(choices=[('missing_payment', 'Missing Payment'), ('orphan_charge', 'Orphan Charge'), ('orphan_refund', 'Orphan Refund'), ('duplicate_charge', 'Duplicate Charge'), ('amount_mismatch', 'Amount Mismatch'), ('charged_after_cancellation', 'Charged After Cancellation'), ('failed_payment', 'Failed Payment'), ('pending_payment', 'Pending Payment'), ('partial_refund', 'Partial Refund'), ('refund_of_completed_order', 'Refund Of Completed Order'), ('currency_mismatch', 'Currency Mismatch'), ('late_settlement', 'Late Settlement'), ('rounding_variance', 'Rounding Variance'), ('data_quality', 'Data Quality')], db_index=True, max_length=32),
        ),
    ]
