# Generated by Django 6.1.1 on 2026-09-04 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orders_file_name', models.CharField(max_length=255)),
                ('payments_file_name', models.CharField(max_length=255)),
                ('order_row_count', models.PositiveIntegerField(default=0)),
                ('payment_row_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=64)),
                ('normalized_id', models.CharField(db_index=True, max_length=64)),
                ('order_date', models.DateTimeField()),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], max_length=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ingestion.importbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'normalized_id'], name='ingestion_o_batch_i_936e13_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'normalized_id'), name='uniq_order_per_batch')],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(db_index=True, max_length=64)),
                ('normalized_order_ref', models.CharField(db_index=True, max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_settled', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('charge', 'Charge'), ('refund', 'Refund')], max_length=16)),
                ('status', models.CharField(choices=[('settled', 'Settled'), ('pending', 'Pending'), ('failed', 'Failed')], max_length=16)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='ingestion.importbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'normalized_order_ref'], name='ingestion_p_batch_i_8ea77d_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch', 'transaction_ref'), name='uniq_txn_per_batch')],
            },
        ),
    ]
